import { ArrowUpRight, ArrowDown, Download } from 'lucide-react';

const github = 'https://github.com/VictorCabaleiroValado';
const project = github + '/ML-Classifier-for-Fault-Diagnosis-in-Rotary-Machines';
const linkedin = 'https://www.linkedin.com/in/victor-cabaleiro-valado/';
export default function Home() {
 return <main>
  <a className="skip" href="#content">Skip to content</a>
  <header className="nav"><a className="wordmark" href="#">VCV<span> / </span><small>Victor Cabaleiro Valado</small></a><nav aria-label="Main navigation"><a href="#experience">Experience</a><a href="#work">Projects</a><a href="#expertise">Toolkits</a><a href="#education">Education</a><a href={linkedin} target="_blank" rel="noreferrer">Let's connect <ArrowUpRight size={16}/></a></nav></header>
  <section className="hero wrap" id="content"><div className="hero-copy"><p className="eyebrow"><span className="dot"/> DATA ANALYTICS · APPLIED AI</p><h1>Victor<br/><em>Cabaleiro Valado</em></h1><p className="hero-role">Data Analyst &amp;<br/>AI Innovation Analyst</p><p className="intro">Senior Graduate Assistant at the University of Arkansas. I combine engineering, statistics and applied AI to turn complex data into practical decisions.</p><div className="actions"><a className="button primary" href="#work">Explore my work <ArrowDown size={18}/></a><a className="button secondary" href="/Victor_Cabaleiro_Resume.pdf" download>Download résumé <Download size={18}/></a></div><p className="hero-meta">UNIVERSITY OF ARKANSAS <span>↗</span> FAYETTEVILLE, AR</p></div><aside className="portrait"><div className="portrait-top"><span>ENGINEERING × STATISTICS</span><span>01 / PROFILE</span></div><img src="/victor-business.png" alt="Victor Cabaleiro Valado" width="2048" height="3072"/><div className="portrait-bottom"><p>Victor Cabaleiro Valado</p><span>Data Analyst & AI Innovation Analyst</span><div className="portrait-rule"/><small>M.S. Statistics & Computational Analytics<br/>Expected May 2027</small></div></aside></section>
  <div className="discipline wrap"><span>FROM SIGNALS TO STRATEGY</span><p>Statistical thinking.</p><p>Engineering rigor.</p><p>Real-world application.</p></div>

 <section className="experience wrap section" id="experience"><div className="section-heading"><h2>1. Experience</h2><p className="section-intro">Working across institutional analytics and applied AI at the University of Arkansas.</p></div><div className="roles"><article className="role"><div className="role-date">2026 — PRESENT<span>Arkansas · Part-time</span></div><div><p className="organization">UNIVERSITY OF ARKANSAS</p><h3>AI Innovation Analyst GA</h3><p>Developing and evaluating AI agents and proof-of-concept solutions with Microsoft Fabric, semantic models and enterprise data.</p><ul><li>Design prompts, retrieval strategies and workflows for more relevant, reliable responses.</li><li>Build evaluation methods to assess accuracy, usability and limitations.</li></ul><div className="tags"><span>Applied AI</span><span>Microsoft Fabric</span><span>Evaluation</span></div></div></article><article className="role"><div className="role-date">2025 — PRESENT<span>Arkansas · Part-time</span></div><div><p className="organization">UNIVERSITY OF ARKANSAS · VCFA</p><h3>Data Analyst GA</h3><p>Supporting strategic university initiatives through statistical analysis, data preparation and business intelligence.</p><ul><li>Develop analytical reports and dashboards with Microsoft Fabric, Power BI, SQL and Python.</li><li>Clean and validate institutional data; automate preparation and reporting workflows.</li></ul><div className="tags"><span>Python & SQL</span><span>Power BI</span><span>Statistics</span></div></div></article><article className="role"><div className="role-date">2022 — 2025<span>Madrid, Spain · Part-time</span></div><div><p className="organization">MSH MULTIPLE FAMILY OFFICE</p><h3>Administrative Assistant</h3><p>Managed client and operational records, standardized documentation and coordinated processes across stakeholders.</p></div></article></div></section>
 <section className="work-section" id="work"><div className="wrap"><div className="section-heading"><h2>2. Projects</h2></div><article className="project"><figure className="project-cover"><img src="/rotary-diagnostics-cover.png" alt="Concept illustration of a motor, bearings and vibration signals used in machine fault diagnosis" width="1672" height="941" loading="lazy"/><figcaption>ROTARY MACHINE DIAGNOSTICS <span>Concept illustration</span></figcaption></figure><div className="project-copy"><p className="project-kicker">MACHINE LEARNING · ENGINEERING DIAGNOSTICS</p><h3>Fault Diagnosis in<br/>Rotary Machines</h3><p>Machines vibrate differently when something is wrong. This project uses accelerometer measurements to help distinguish normal operation from mechanical faults. I built a Python tool that connects sensor data, signal processing and machine learning in an interactive analysis workflow.</p><div className="tags"><span>Python</span><span>scikit-learn</span><span>Signal processing</span></div><a className="button dark-button" href={project} target="_blank" rel="noreferrer">Explore the repository <ArrowUpRight size={18}/></a><a className="text-link" href={project + '/blob/main/docs/DATA_PROVENANCE.md'} target="_blank" rel="noreferrer">Read the data & methodology notes <ArrowUpRight size={15}/></a></div><div className="project-evidence"><p className="evidence-label">THE WORKFLOW</p><ol className="pipeline"><li><span>01</span><div><strong>Record the vibration</strong><small>Collect measurements from 9 sensor channels.</small></div></li><li><span>02</span><div><strong>Find useful patterns</strong><small>Summarize the signal in time and frequency.</small></div></li><li><span>03</span><div><strong>Compare fault predictions</strong><small>Train classifiers and evaluate on held-out data.</small></div></li></ol><div className="project-numbers"><div><strong>975</strong><span>original 25 RPM measurements</span></div><div><strong>39</strong><span>automated tests passing</span></div></div><p className="evidence-note">An academic project with traceable 25 RPM data and documented limits for historical datasets. Code, tests and methodology are open for review.</p></div></article></div></section>
 <section className="toolkit section" id="expertise"><div className="wrap"><div className="section-heading"><h2>3. Toolkits</h2></div><div className="skill-grid"><article><span className="skill-no">01</span><h3>Analytics & BI</h3><p>From reliable datasets to clear reporting and informed decisions.</p><div className="tags"><span>Microsoft Fabric</span><span>Power BI</span><span>SQL</span><span>Excel</span></div></article><article><span className="skill-no">02</span><h3>Statistics & ML</h3><p>Exploratory analysis, predictive modeling and careful evaluation.</p><div className="tags"><span>Python</span><span>Pandas</span><span>NumPy</span><span>SciPy</span><span>scikit-learn</span></div></article><article><span className="skill-no">03</span><h3>AI & Engineering</h3><p>Semantic models, AI agents and the engineering foundations to connect systems.</p><div className="tags"><span>AI evaluation</span><span>MATLAB</span><span>C</span><span>Java</span><span>VHDL</span></div></article></div></div></section>
 <section className="education wrap section" id="education"><div className="section-heading"><h2>4. Education</h2></div><div className="education-list"><article><span>2025 — 2027</span><div><h3>M.S. Statistics & Computational Analytics</h3><p>University of Arkansas</p><small>Expected graduation · May 2027</small></div></article><article><span>2024 — 2025</span><div><h3>Exchange Year</h3><p>University of Arkansas</p><small>Fayetteville, Arkansas</small></div></article><article><span>2019 — 2024</span><div><h3>B.S. Telecommunication Technologies Engineering</h3><p>Universidad Carlos III de Madrid</p><small>Engineering foundations across computation, signals and systems</small></div></article></div></section>
 <section className="contact wrap section" id="contact"><p className="eyebrow">LET'S BUILD SOMETHING USEFUL</p><h2>Your next challenge.<br/><span>My analytical mindset.</span></h2><p>I'm interested in opportunities in data analytics, data science, business intelligence and applied AI. Let's talk about where I can contribute.</p><div className="actions"><a className="button primary" href="mailto:vc024@uark.edu">Get in touch <ArrowUpRight size={18}/></a><a className="button secondary" href="/Victor_Cabaleiro_Resume.pdf" download>Download résumé <Download size={18}/></a></div><div className="contact-links"><a href={linkedin} target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={16}/></a><a href={github} target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={16}/></a><a href="mailto:vc024@uark.edu">vc024@uark.edu</a></div></section>
 <footer className="wrap"><span>© 2026 Victor Cabaleiro Valado</span><span>Fayetteville, AR · Spanish / English</span><a href="#content">Back to top ↑</a></footer>
 </main>;
}
